POST http://localhost:3000/api/comercios
Content-Type: application/json

{
    "nombre": "Nombre del comercio",
    "cif": "CIF123",
    "direccion": "Dirección del comercio",
    "email": "correo@comercio.com",
    "telefono": "123456789",
    "idPagina": 1
}

###

PUT http://localhost:3000/api/comercios/CIF123
Content-Type: application/json

{
    "nombre": "Nuevo nombre del comercio",
    "cif": "CIF123",
    "direccion": "Nueva dirección del comercio",
    "email": "nuevo_correo@comercio.com",
    "telefono": "987654321",
    "idPagina": 2
}

###
DELETE http://localhost:3000/api/comercios/CIF123

###

PATCH http://localhost:3000/api/comercios/CIF123
Content-Type: application/json

{
    "direccion": "Nueva dirección del comercio"
}