GET http://localhost:3000/

##

POST http://localhost:3000/cursos/programacion
Content-Type: application/json

{
    "titulo": "Aprende Node.js"
}

##
GET http://localhost:3000/api/cursos/programacion/python?ordenar=vistas HTTP/1.1

##

PUT http://localhost:3000/ HTTP/1.1